### ISSUE TITLE
Typos en la publicación de "Aplicaciones Real-Time de Alta Escala"

### ISSUE THREAD

**Issue by juandc** [sergiodxa/personal-site#149]
- _"... Hacer **resto** reduce la cantidad de información ..."_ ([#L69](https://github.com/sergiodxa/personal-site/blob/master/pages/essays/aplicaciones-real-time-alta-escala.mdx#L69))
- _"Es importante tener en **cuanta** que esto puede ..."_ ([#L71](https://github.com/sergiodxa/personal-site/blob/master/pages/essays/aplicaciones-real-time-alta-escala.mdx#L71))

**Comment by sergiodxa** [comment]
Gracias! Ya están corregidos! 🙏
